# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: Node ${{ matrix.node }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      fail-fast: true
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        node:
          # - 10 - The library supports Node 10, but the tests don't
          - 12
          - 13
          - 14
          # - 15

    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Install Node ${{ matrix.node }}
        uses: actions/setup-node@v2-beta
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: npm ci

      - name: Run linters
        run: npm run lint

      - name: Build the code
        run: npm run build-bundle

      #- name: Run tests
      #  run: npm run coverage

      #- name: Send code coverage results to Coveralls
      #  uses: coverallsapp/github-action@v1.1.0
      #  with:
      #    github-token: ${{ secrets.GITHUB_TOKEN }}
      #    parallel: true
  publish:
    name: Publish to NPM
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: build

    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v2-beta
        with:
          node-version: 12

      - name: Install dependencies
        run: npm ci

      - name: Build the code
        run: npm run build-bundle

      - name: Publish to NPM
        uses: ./
        with:
          token: ${{ secrets.NPM_PUBLISH_TOKEN }}
